version: "3"

services:
  elasticsearch:
    image: elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
  db:
    image: postgres:15
    container_name: db
    env_file:
      - src/.env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./etl/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - db_data:/var/lib/postgresql/data/
  backend:
    build: src/.
    env_file:
      - src/.env
    volumes:
      - ./src:/srv/app
    ports:
      - 8080:8080

  redis:
    image: redis:5.0.7-alpine
    env_file:
      - src/.env
    ports:
      - "6379:6379"
volumes:
  db_data: